### ISSUE TITLE
Event Blocker always blocks Real-Time message

### ISSUE THREAD

**Issue by aldenis** [x42/midifilter.lv2#13] opened 2017-01-21 23:52 UTC
Hi,
The MIDI Event Blocker plugin always blocks MIDI realtime messages (Start/Stop/Continue/Clock), whatever the setting for "Sysex/RT messages" is.

Im using release 20161230-1 from Debian sid, using Carla as a host. Same behavior with 20160825-1kxstudio1
Thanks!

**Comment by x42** [comment] 2017-01-22 01:16
I cannot reproduce this with jalv.gtk nor Ardour.
Carla is not in debian, so I can't test. Could it be that Carla does not deliver those events to plugins?   Could you try with the midi-thru midifilter (that just passes all events through as-is)?

**Comment by aldenis** [comment] 2017-01-22 11:28
Damn, it works with jalv.gtk!
All in Carla: using passthru from midifilter (LV2), clock is lost ; using midiNotchFilter from pizmidi plugins (VST), clock is ok ; using internal Midi through (Carla internal), clock is ok.
So the bug is in Carla, only for *LV2* MIDI plugins.
It might be related to https://github.com/falkTX/Carla/issues/453

I would have sworn the bug was in x42 midifilter, since I had tested with pizmidi midiNotchFilter, and it worked in Carla.
Sorry for the noise.

**Comment by x42** [comment] 2017-01-22 21:18
No problem. and thanks for checking and following up.
I also cannot explain this from the midifilter's source. Closing this.

**Closed by x42** 2017-01-22 21:18 UTC
